export const INITIAL_PAGI_FORM = {
  current: 1,
  page_size: 10,
};

// http://www.counect.com/en-us/?support_data_analytics
export const LOCALES = {
  store_id: '商户ID',
  industry: '业态名称',
  department: '所属部门',
  account_manager: '客户经理',
  store_status: '商户状态',
  store_stat: '商户状态',
  health_stat: '健康状态',
  yesterday_health: '昨日体检',
  '30d_sales': '近30日交易额(元)',
  '30d_compare_rate': '近30日环比率',
  current: '当前页',
  page_size: '显示条数',
  store_name: '商户名称',
  today_sales: '今日交易额(元)',
  yesterday_sales: '昨日交易额(元)',
  rank: '排名',
  sales: '交易额(元)',
  amount: '实收金额(元)',
  amount_range: '交易金额',
  date_range: '查询时间',
  industry_name: '业态名称',
  transaction: '交易数(笔)',
  acreage: '面积(m2)',
  contact_name: '联系人',
  contact_phone: '联系方式',
  address: '省市区',
  address_detail: '详细地址',
  ats: '单笔交易额(元/笔)',
  spm: '坪效(元/m2)',
  softwares: '使用软件',
  saas_order_number: 'SaaS订单号',
  receipt_order_number: '小票订单号',
  pay_order_number: '支付订单号',
  trade_time: '交易时间',
  trade_type: '交易类型',
  sn: '收款设备',
  pay_type: '支付类型',
  pay_amount: '支付金额(元)',
  pay_time: '支付时间',
  pay_stat: '支付状态',
  pay_channel: '支付通道',
  soft_name: 'SaaS名称',
  pay_id: '支付ID',
  current_value: '本期数值',
  last_value: '上期数值',
  time: '时间',
  saas_sales: 'SaaS交易额(元)',
  receipt_sales: '小票交易额(元)',
  sunmi_sales: '支付交易额(元)',
  saas_transaction: 'SaaS交易数(笔)',
  receipt_transaction: '小票交易数(笔)',
  sunmi_transaction: '支付交易数(笔)',
  saas_ats: 'SaaS单笔交易额(元/笔)',
  receipt_ats: '小票单笔交易额(元/笔)',
  sunmi_ats: '支付单笔交易额(元/笔)',
  saas_spm: 'SaaS坪效(元/m2)',
  receipt_spm: '小票坪效(元/m2)',
  sunmi_spm: '支付坪效(元/m2)',
  total_store_num: '总商户数(家)',
  increase_store_num: '新增商户数(家)',
  pass_year_value: '去年本期数值',
  store_num: '商户数(家)',
  stock_store_num: '存量商户数(家)',
  sply: '同比增长率',
  lp: '环比增长率',
  change_time: '操作时间',
  change_type: '操作类型',
  receipt_id: '小票ID',
  video_id: '视频ID',
  field_name: '',
};

export type FieldKey = keyof typeof LOCALES;

export const INPUT_FIELDS = {
  store: '',
  industry: undefined,
  department: undefined,
  accountManager: undefined,
  storeStatus: undefined,
  healthStatus: undefined,
  current: 1,
  pageSize: 10,
};

export interface Field {
  id: string;
  label: string;
}
