version: '3.1'

services:
  lex:
    container_name: lex
    image: node:latest
    environment:
      # if you have your own mysql, config it here, and disable the 'mysql' config blow
      - MYSQL_URL=lex-mysql # links will maintain /etc/hosts, just use 'container_name'
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=root
      - MYSQL_PASSWD=123456
      - MYSQL_DATABASE=Lex
      - SUNMI_PROD_URL=http://localhost:3000
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
    working_dir: /app
    command: 'npx nodemon'
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  # https://github.com/typeorm/typeorm/issues/2093
  # https://github.com/mysqljs/mysql/issues/2013
  mysql:
    container_name: lex-mysql
    image: mysql:5.6
    volumes:
      # 初始化数据库SQL
      # https://stackoverflow.com/questions/38504257/mysql-scripts-in-docker-entrypoint-initdb-are-not-executed
      - ./server/database/sql:/docker-entrypoint-initdb.d
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    ports:
      - 3306:3306
