version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npx yarn
      - run: npm run build:master
      - setup_remote_docker
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build --tag lexland/lex:latest .
      - run: docker push lexland/lex:latest
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - '34:99:74:78:a0:a0:76:78:a5:88:f4:de:b4:f4:f3:2a'
      - run:
          name: Deploy Over SSH
          command: |
            scp -f docker $SSH_USER@$SSH_HOST:/root/lex/docker
            ssh $SSH_USER@$SSH_HOST "cd /root/lex/docker && docker-compose down && docker-compose up -d"

# SUNMI_PROD_URL=https://lex-land.online SUNMI_ENV=master
# =https://lex-land.online

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
