version: 2

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npx yarn
      # 使用docker内host
      - run: PROD_API_URL=https://lex-land.cloud npm run build
      # https://circleci.com/docs/2.0/building-docker-images/
      # docker 集群分配新的 docker 引擎
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: npm run docker:build
      - run: npm run docker:push
  deploy:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - 'a6:f7:79:2b:9f:58:f2:db:1e:2e:4d:14:95:29:4c:c3'
      - run:
          name: Copy Files
          command: |
            scp -r docker/** $SSH_USER@$SSH_HOST:/root
      - run:
          name: Deploy Over SSH
          command: |
            # docker stack deploy 类似 service xx reload
            ssh $SSH_USER@$SSH_HOST "docker-compose pull && docker stack deploy --compose-file docker-compose.yml lex"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
