version: '2'
services:
  mysql:
    image: mysql:5.6
    container_name: test-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'Lex'
    volumes:
      - ./temp/mysql:/var/lib/mysql
    # 添加默认排序规则
    # https://stackoverflow.com/questions/45729326/how-to-change-the-default-character-set-of-mysql-using-docker-compose
    command:
      [
        'mysqld',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
    networks:
      - net-mysql


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: test-phpmyadmin
    ports:
      - '8080:80'
    environment:
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '123456'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'Lex'
      PMA_HOST: test-mysql
    networks:
      - net-mysql

networks:
  net-mysql:
