version: "2"
services:
  mysql:
    image: mysql:5.6
    container_name: test-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: 'Lex'
    volumes:
      - ../cache/mysql:/var/lib/mysql
    networks:
      - net-mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: test-phpmyadmin
    ports:
      - "8080:80"
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: 'Lex'
      PMA_HOST: test-mysql
    networks:
      - net-mysql

networks:
  net-mysql:
