version: '3.1'

services:
  lex-nginx:
    image: nginx:latest
    container_name: lex-nginx
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    links:
      - lex-node
    depends_on:
      - lex-node
    ports:
      - 80:80
      - 443:443

  lex-node:
    container_name: lex-node
    image: lexland/lex:latest
    environment:
      - NODE_ENV=production
      - PROD_API_URL=https://lex-land.cloud
      - BUILD_TAG
    command: npx next start
    ports:
      - '3000:3000'
